#Copyright (c) 2022 All project authors. All rights reserved.
#
#This source code is licensed under Apache 2.0 License.

server:
  port: 8083

nebula:
  ngbatis:
    session-life-length: 300000
    check-fixed-rate: 300000
    # space name needs to be informed through annotations(@Space) or xml(space="test")
    # default false(false: Session pool map will not be initialized)
    use-session-pool: true
    test-space-placeholder: cmqa
    # 是否启用 props 作为栏位时，直接映射到实体对象的属性。
    # 会改变原有的映射方式。请检查是否影响原有业务逻辑。
    # 如果对原有业务产生影响，请设置为 false
    # Whether to enable props as fields directly mapped to entity objects. 
    # It will change the original mapping method. Please check whether it affects the original business logic.
    # If it affects the original business, please set it to false
    enable-prop-mapping: true
  hosts: 139.9.187.207:9669
  username: root
  password: U3RhclNoYWRvd18wOTE5
  space: test
  pool-config:
    min-conns-size: 0
    max-conns-size: 10
    timeout: 6000
    idle-time: 0
    interval-idle: -1
    wait-time: 0
    min-cluster-health-rate: 1.0
    enable-ssl: false
    
# 开启 nGQL 输出
logging:
  level:
    org.nebula.contrib: DEBUG